{{- $ := . -}}
{{- range $.Values.secret }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .name }}
  labels:
    app: {{ .ame }}
{{- if .type }}    
type: {{ .type }}
{{- end }}
data:
  {{- range $key, $value := .data }}
    {{ $key }}: >-
      {{ $value | b64enc }}
  {{- end }}
{{- if .immutable }}    
immutable: {{ .immutable | default false }}    
{{- end }}
{{- end }}
